Uncomment this line to define a global platform for your project
platform :ios, ‘8.0’

target 'petbnb' do/Users/merrichuffstutler/Projects/Hackathon/the-postmen-repo/petbnb/Podfile

end

target 'petbnbTests' do

end

